import React, { useState } from 'react';
import {
  FileText,
  Download,
  Sparkles,
  Printer,
  Calendar,
  CheckCircle2,
} from 'lucide-react';
import { useWarehouse } from '../context/WarehouseContext';
import { WarehouseReport } from '../types';

export const ReportsCenterView: React.FC = () => {
  const { reports, addReport, metrics } = useWarehouse();
  const [selectedReportId, setSelectedReportId] = useState<string>(reports[0]?.id || 'rep-daily-01');
  const [generating, setGenerating] = useState<boolean>(false);

  const selectedReport = reports.find((r) => r.id === selectedReportId) || reports[0];

  const handleGenerateNewReport = (
    type: 'daily_warehouse_report' | 'inventory_health_report' | 'order_fulfillment_report'
  ) => {
    setGenerating(true);
    setTimeout(() => {
      const typeTitleMap = {
        daily_warehouse_report: 'Daily Shift Operations & Fulfillment Briefing',
        inventory_health_report: 'Inventory Health & Reorder Velocity Audit',
        order_fulfillment_report: 'Outbound SLA & Carrier Performance Report',
      };

      const newRep: WarehouseReport = {
        id: `rep-${Date.now()}`,
        type,
        title: `${typeTitleMap[type]} - ${new Date().toLocaleDateString('en-US', {
          month: 'short',
          day: 'numeric',
          year: 'numeric',
        })}`,
        generatedAt: `Today, ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} UTC`,
        generatedBy: 'Nexus AI Autonomous Director',
        period: 'Active Shift Alpha',
        executiveSummary: `Automated operational audit covering ${metrics.fulfilledToday} fulfilled orders, ${metrics.slaComplianceRate}% SLA compliance, and zero critical dispatch blockages.`,
        kpis: [
          { label: 'SLA Compliance', value: `${metrics.slaComplianceRate}%`, trend: 'Target: 98.0%', isPositive: true },
          { label: 'Orders Fulfilled', value: `${metrics.fulfilledToday} / ${metrics.totalOrdersToday}`, trend: 'Nominal', isPositive: true },
          { label: 'ATP Accuracy', value: `${metrics.atpAccuracyRate}%`, trend: 'Audited', isPositive: true },
          { label: 'Pick Velocity', value: `${metrics.throughputPerHour} u/hr`, trend: '+12 u/hr vs target', isPositive: true },
        ],
        keyFindings: [
          `Fulfillment throughput maintained at ${metrics.throughputPerHour} units/hour across Shift Alpha.`,
          `0 critical SLA breaches recorded; 1 VIP stockout prevented through proactive buffer allocation.`,
          `Supplier replenishment orders queued for 2 critical SKUs.`,
        ],
        recommendedActionItems: [
          { priority: 'High', action: 'Approve pending Smart Reorder POs in Reorders tab', owner: 'Inventory Lead' },
          { priority: 'Medium', action: 'Monitor Packing Station #02 queue for poly-mailer backlog', owner: 'Shift Supervisor' },
        ],
      };

      addReport(newRep);
      setSelectedReportId(newRep.id);
      setGenerating(false);
    }, 800);
  };

  const handleExportCSV = () => {
    if (!selectedReport) return;
    const csvContent =
      'data:text/csv;charset=utf-8,' +
      `Report Title,${selectedReport.title}\n` +
      `Generated At,${selectedReport.generatedAt}\n` +
      `Generated By,${selectedReport.generatedBy}\n` +
      `Executive Summary,"${selectedReport.executiveSummary}"\n\n` +
      `KPI Label,Value,Trend\n` +
      (selectedReport.kpis || []).map((k) => `"${k.label}","${k.value}","${k.trend || ''}"`).join('\n') +
      `\n\nKey Findings\n` +
      (selectedReport.keyFindings || []).map((h) => `"${h}"`).join('\n');

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `${selectedReport.title.replace(/ /g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="p-6 rounded-2xl bg-slate-900/90 border border-slate-800 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-blue-500/20 ring-1 ring-blue-400/30">
            <FileText className="w-7 h-7 text-white" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold text-slate-100">
                AI Warehouse Intelligence Reports & Briefings
              </h2>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-950 text-blue-300 border border-blue-800">
                ENTERPRISE EXPORTABLE
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Automated shift handoffs, executive performance summaries, and inventory health reports ready for CSV/PDF export.
            </p>
          </div>
        </div>

        {/* Generate Report Buttons */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => handleGenerateNewReport('daily_warehouse_report')}
            disabled={generating}
            className="px-3.5 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs transition cursor-pointer flex items-center gap-1.5 shadow-md disabled:opacity-50"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Generate Daily Briefing</span>
          </button>
          <button
            onClick={() => handleGenerateNewReport('inventory_health_report')}
            disabled={generating}
            className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs transition cursor-pointer flex items-center gap-1.5 disabled:opacity-50"
          >
            <span>Inventory Health Audit</span>
          </button>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Report Archive */}
        <div className="lg:col-span-4 p-5 rounded-2xl bg-slate-900/90 border border-slate-800 shadow-xl space-y-4">
          <div className="flex items-center justify-between pb-2 border-b border-slate-800">
            <h3 className="font-semibold text-sm text-slate-100 flex items-center gap-2">
              <Calendar className="w-4 h-4 text-blue-400" />
              Generated Report Archive
            </h3>
            <span className="text-xs text-slate-400 font-mono">{(reports || []).length} Total</span>
          </div>

          <div className="space-y-2 max-h-[550px] overflow-y-auto pr-1">
            {(reports || []).map((rep) => {
              const isSelected = rep.id === selectedReportId;
              return (
                <button
                  key={rep.id}
                  onClick={() => setSelectedReportId(rep.id)}
                  className={`w-full p-3.5 rounded-xl text-left border transition cursor-pointer flex flex-col gap-1.5 ${
                    isSelected
                      ? 'bg-blue-950/40 border-blue-600 shadow-md'
                      : 'bg-slate-950/60 border-slate-800 hover:bg-slate-800/60 text-slate-300'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-800 text-blue-300 font-mono capitalize">
                      {rep.type.replace(/_/g, ' ')}
                    </span>
                    <span className="text-[10px] text-slate-500 font-mono">{rep.generatedAt}</span>
                  </div>
                  <h4 className="font-bold text-xs text-slate-100 line-clamp-1">{rep.title}</h4>
                  <p className="text-[11px] text-slate-400 line-clamp-2 leading-relaxed">
                    {rep.executiveSummary}
                  </p>
                </button>
              );
            })}
          </div>
        </div>

        {/* Right Column: Full Report Preview */}
        <div className="lg:col-span-8 p-6 rounded-2xl bg-slate-900/90 border border-slate-800 shadow-xl space-y-6 flex flex-col justify-between">
          {selectedReport ? (
            <div className="space-y-6">
              {/* Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-slate-800 gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="px-2.5 py-0.5 rounded text-xs font-bold bg-blue-950 text-blue-300 border border-blue-800 capitalize">
                      {selectedReport.type.replace(/_/g, ' ')}
                    </span>
                    <span className="text-xs text-slate-400 font-mono">
                      Generated: {selectedReport.generatedAt}
                    </span>
                  </div>
                  <h3 className="text-lg font-bold text-slate-100 mt-1">{selectedReport.title}</h3>
                  <div className="text-xs text-slate-400">
                    Compiled by: <strong className="text-slate-300">{selectedReport.generatedBy}</strong> • Period: <span className="text-slate-300">{selectedReport.period}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={handleExportCSV}
                    className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition cursor-pointer flex items-center gap-1.5"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Export CSV</span>
                  </button>
                  <button
                    onClick={() => window.print()}
                    className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition cursor-pointer"
                    title="Print Document"
                  >
                    <Printer className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Narrative Summary */}
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
                <span className="text-[11px] font-bold text-blue-400 uppercase tracking-wider">
                  Executive Narrative Summary
                </span>
                <p className="text-xs text-slate-200 leading-relaxed">
                  {selectedReport.executiveSummary}
                </p>
              </div>

              {/* KPIs */}
              <div className="space-y-2">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  Core Shift Telemetry & Metrics
                </span>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs">
                  {selectedReport.kpis.map((kpi, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-center"
                    >
                      <div className="text-[10px] text-slate-400">{kpi.label}</div>
                      <div className="text-sm font-bold text-cyan-300 mt-0.5">{kpi.value}</div>
                      {kpi.trend && (
                        <div className="text-[10px] text-emerald-400 mt-0.5">{kpi.trend}</div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Highlights */}
              <div className="space-y-2">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  Operational Findings & Key Highlights
                </span>
                <div className="space-y-2">
                  {selectedReport.keyFindings.map((hl, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-xl bg-slate-950/60 border border-slate-800/80 flex items-start gap-2.5 text-xs text-slate-200"
                    >
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                      <span className="leading-relaxed">{hl}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Action Items */}
              {selectedReport.recommendedActionItems && (
                <div className="space-y-2">
                  <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                    Assigned Action Directives
                  </span>
                  <div className="space-y-1.5">
                    {selectedReport.recommendedActionItems.map((item, idx) => (
                      <div
                        key={idx}
                        className="p-2.5 rounded-lg bg-slate-950 border border-slate-800 flex items-center justify-between text-xs font-mono"
                      >
                        <span className="text-slate-200">{item.action}</span>
                        <div className="flex items-center gap-2">
                          <span className="text-slate-500">Owner: {item.owner}</span>
                          <span
                            className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                              item.priority === 'High'
                                ? 'bg-rose-950 text-rose-300'
                                : 'bg-slate-800 text-slate-300'
                            }`}
                          >
                            {item.priority}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="p-12 text-center text-xs text-slate-400">
              No report selected. Choose a report from the left archive.
            </div>
          )}

          <div className="pt-4 border-t border-slate-800 flex items-center justify-between text-xs text-slate-500 font-mono">
            <span>Enterprise Compliance: Validated for Shift Alpha Audit Records</span>
            <span>HUB-07 Dispatch Server</span>
          </div>
        </div>
      </div>
    </div>
  );
};
